name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: node build.js
      - name: Push built files to GitHub
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
          git add dist/auth.min.js
          git commit -m 'chore: auto-build by GitHub Actions' || echo "No changes"
          git push
      - name: Tag new release version
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          # Get latest tag
          LATEST_TAG=$(git tag --sort=-v:refname | head -n 1)
          echo "Latest tag is: $LATEST_TAG"

          if [[ "$LATEST_TAG" =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
            MAJOR=${BASH_REMATCH[1]}
            MINOR=${BASH_REMATCH[2]}
            PATCH=${BASH_REMATCH[3]}
            PATCH=$((PATCH + 1))
            NEW_TAG="v$MAJOR.$MINOR.$PATCH"
          else
            NEW_TAG="v1.0.0"
          fi

          echo "Creating new tag: $NEW_TAG"
          git tag -f $NEW_TAG
          git push -f origin $NEW_TAG
